name: Notify

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  tg_notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Telegram Message Notify
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          message: ${{ github.actor }} updated the repository ${{ github.repository}} ${{ github.event.head_commit.message }}
